-- ************************************** "phlogiston_u_roles"

CREATE TABLE "phlogiston_u_roles"
(
 "id"   bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
 "name" varchar(50) NOT NULL UNIQUE,
 "description" varchar(100) NOT NULL,
 CONSTRAINT "PK_phlogiston_u_roles" PRIMARY KEY ( "id" )
);

-- ************************************** "phlogiston_user"

CREATE TABLE "phlogiston_user"
(
    "id"                        bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "login"                     varchar(30) NOT NULL,
    "password"                  varchar(128) NOT NULL,
    "email"                     varchar(45) NOT NULL,
    "last_name"                 varchar(50) NOT NULL,
    "first_name"                varchar(50) NOT NULL,
    "middle_name"               varchar(50) NULL,
    "organisation"              varchar(500) NULL,
    "position"                  varchar(70) NULL,
    "phone"                     varchar(50) NULL,
    "create_date"               timestamp with time zone NOT NULL,
    "role_id"                   bigint NOT NULL,
    CONSTRAINT "PK_phlogiston_user" PRIMARY KEY ( "id" ),
    CONSTRAINT "AK1_phlogiston_user" UNIQUE ( "login" )
);



