-- ************************************** "phlogiston_u_roles"

CREATE TABLE "phlogiston_u_roles"
(
    "id"          bigint       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name"        varchar(50)  NOT NULL UNIQUE,
    "description" varchar(100) NOT NULL,
    CONSTRAINT "PK_phlogiston_u_roles" PRIMARY KEY ("id")
);

-- ************************************** "phlogiston_users"

CREATE TABLE "phlogiston_users"
(
    "id"                        bigint                   NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "username"                  varchar(30)              NOT NULL,
    "active"                    boolean                  NOT NULL,
    "password"                  varchar(128)             NOT NULL,
    "email"                     varchar(45)              NOT NULL,
    "last_name"                 varchar(50)              NOT NULL,
    "first_name"                varchar(50)              NOT NULL,
    "middle_name"               varchar(50) NULL,
    "organisation"              varchar(70) NULL,
    "position"                  varchar(70) NULL,
    "phone"                     varchar(50) NULL,
    "create_date"               timestamp with time zone NOT NULL,
    "last_time_update_password" timestamp with time zone NOT NULL,
    "role_id"                   bigint                   NOT NULL,
    "failed_login_counter"      int                      NOT NULL,
    "invalid_password_time"     timestamp with time zone NULL,
    "uuid"                      UUID                     NOT NULL,

    CONSTRAINT "PK_phlogiston_user" PRIMARY KEY ("id"),
    CONSTRAINT "AK1_phlogiston_user" UNIQUE ("username"),
    CONSTRAINT "AK2_phlogiston_user" UNIQUE ("uuid")
);


